# Common plugin properties
plugin.id=${packagePrefix}.${pluginName}
plugin.class=${packagePrefix}.${pluginName}.${pluginName}Plugin
plugin.version=${version}
plugin.description=
plugin.provider=
plugin.dependencies=
plugin.order=100000
