spring:
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: refresh
springdoc:
  group-configs:
    - group: default
      displayName: default
      packagesToScan: gj.demo